### PR TITLE
 Set the correct toggled state as soon as the solution is fully loaded

### LINKED ISSUE #13: Toolbar button is initially incorrect
Opened VS, started debugging, opened options without changing anything:

image

After clicking, the icon stays untoggled (because it toggled, like it is supposed to).

I think this is what was behind https://github.com/tunnelvisionlabs/JustMyCodeToggle/issues/12. I don't know why I worked around this so long without reporting it—keyboard shortcut makes life easy, I guess! 😄

### PR DESCRIPTION
**Pull request by jnm2**
Fixes #13.

/cc @sharwell, @jcansdale

### CODE REVIEW

File: Tvl.VisualStudio.JustMyCodeToggle/JustMyCodeTogglePackage.cs [hunk 1]
```diff
@@ -26,27 +29,19 @@ public JustMyCodeTogglePackage()
...
-                return new VsServiceProviderWrapper(this);
-            }
-        }
-
         public EnvDTE.DTE ApplicationObject
         {
             get
             {
-                return ServiceProvider.GetService(typeof(EnvDTE._DTE)) as EnvDTE.DTE;
+                return GetService(typeof(EnvDTE._DTE)) as EnvDTE.DTE;
```
Comment (jnm2) [inline Tvl.VisualStudio.JustMyCodeToggle/JustMyCodeTogglePackage.cs]: It's either `GetService`, or JTF.Run on `GetServiceAsync` in BeforeQueryStatus and InvokeHandler.

File: Tvl.VisualStudio.JustMyCodeToggle/JustMyCodeTogglePackage.cs [hunk 2]
```diff
@@ -6,14 +6,17 @@ namespace Tvl.VisualStudio.JustMyCodeToggle
...
     using System.Runtime.InteropServices;
+    using System.Threading;
+    using Microsoft.VisualStudio;
     using Microsoft.VisualStudio.Shell;
-    using ErrorHandler = Microsoft.VisualStudio.ErrorHandler;
     using IMenuCommandService = System.ComponentModel.Design.IMenuCommandService;
+    using Task = System.Threading.Tasks.Task;
 
     [Guid(JustMyCodeToggleConstants.guidJustMyCodeTogglePackageString)]
     [PackageRegistration(UseManagedResourcesOnly = true)]
```
Comment (jcansdale) [inline Tvl.VisualStudio.JustMyCodeToggle/JustMyCodeTogglePackage.cs]: I think this should be:
```cs
[PackageRegistration(UseManagedResourcesOnly = true, AllowsBackgroundLoading = true)]
```

`AllowsBackgroundLoading = true` is like a master switch that allows the package to load on a b/g thread.  `PackageAutoLoadFlags.BackgroundLoad` is just a hint for that particular `ProvideAutoLoad`.

File: Tvl.VisualStudio.JustMyCodeToggle/JustMyCodeTogglePackage.cs (hunk 1 above)
Comment (jcansdale) [reply Tvl.VisualStudio.JustMyCodeToggle/JustMyCodeTogglePackage.cs]: I believe it will be called on the UI thread, so GetService is fine.

Comment (jnm2) [reply Tvl.VisualStudio.JustMyCodeToggle/JustMyCodeTogglePackage.cs]: And if somehow it wasn't called on the UI thread, we'd still need to switch to the UI thread because DTE isn't free-threaded, correct? So pretty much no matter what, this needs to be GetService?

Comment (jcansdale) [reply Tvl.VisualStudio.JustMyCodeToggle/JustMyCodeTogglePackage.cs]: I've been using DTE on non-UI threads for years and it generally doesn't care. If you're being pedantic you should assume it isn't free-threaded. 😉

**Comment by jnm2** [comment]
@sharwell I would be much obliged! It's still a thing.

File: Tvl.VisualStudio.JustMyCodeToggle/JustMyCodeTogglePackage.cs [hunk 3]
```diff
@@ -6,14 +6,17 @@ namespace Tvl.VisualStudio.JustMyCodeToggle
...
-    using ErrorHandler = Microsoft.VisualStudio.ErrorHandler;
     using IMenuCommandService = System.ComponentModel.Design.IMenuCommandService;
+    using Task = System.Threading.Tasks.Task;
 
     [Guid(JustMyCodeToggleConstants.guidJustMyCodeTogglePackageString)]
-    [PackageRegistration(UseManagedResourcesOnly = true)]
+    [PackageRegistration(UseManagedResourcesOnly = true, AllowsBackgroundLoading = true)]
     [ProvideMenuResource(1000, 1)]
-    internal class JustMyCodeTogglePackage : Package
+    [ProvideAutoLoad(VSConstants.UICONTEXT.SolutionExistsAndFullyLoaded_string, PackageAutoLoadFlags.BackgroundLoad)]
```
Comment (sharwell) [inline Tvl.VisualStudio.JustMyCodeToggle/JustMyCodeTogglePackage.cs]: 💭 This seems like a reasonable context for this

File: Tvl.VisualStudio.JustMyCodeToggle/JustMyCodeTogglePackage.cs [hunk 4]
```diff
@@ -26,27 +29,19 @@ public JustMyCodeTogglePackage()
...
             {
-                return ServiceProvider.GetService(typeof(EnvDTE._DTE)) as EnvDTE.DTE;
+                return GetService(typeof(EnvDTE._DTE)) as EnvDTE.DTE;
             }
         }
 
-        protected override void Initialize()
+        protected override async Task InitializeAsync(CancellationToken cancellationToken, IProgress<ServiceProgressData> progress)
         {
-            base.Initialize();
```
Comment (sharwell) [inline Tvl.VisualStudio.JustMyCodeToggle/JustMyCodeTogglePackage.cs]: :bulb: It appears code typically calls the base implementation, but it's not sure if this is required:

```csharp
await base.InitializeAsync(cancellationToken, progress);

// Rest of initialization ...
```

File: Tvl.VisualStudio.JustMyCodeToggle/JustMyCodeTogglePackage.cs [hunk 5]
```diff
@@ -26,27 +29,19 @@ public JustMyCodeTogglePackage()
...
+            await JoinableTaskFactory.SwitchToMainThreadAsync();
```
[the remark this answers is not in the document]
Comment (jnm2) [reply Tvl.VisualStudio.JustMyCodeToggle/JustMyCodeTogglePackage.cs]: Good, thanks. ReSharper usually tells me about this. :'(

File: Tvl.VisualStudio.JustMyCodeToggle/JustMyCodeTogglePackage.cs (hunk 4 above)
Comment (jnm2) [reply Tvl.VisualStudio.JustMyCodeToggle/JustMyCodeTogglePackage.cs]: I had checked that it was returning CompletedTask, but the very fact that I had to check makes me suspicious of looking in the first place. Funny enough, this was the last PR before I started leaving base calls in my overrides. :D

**Comment by jnm2** [comment]
@sharwell Updated.

File: Tvl.VisualStudio.JustMyCodeToggle/JustMyCodeTogglePackage.cs [hunk 6]
```diff
@@ -1,19 +1,24 @@
 ﻿// Copyright (c) Tunnel Vision Laboratories, LLC. All Rights Reserved.
 // Licensed under the MIT License. See LICENSE.txt in the project root for license information.
 
+using Microsoft;
```
Comment (sharwell) [inline Tvl.VisualStudio.JustMyCodeToggle/JustMyCodeTogglePackage.cs]: :memo: This should have been inside the namespace, but it also should have been detected by the build. I'll fix it in a follow-up pull request where I enable StyleCop Analyzers.
